<?php


namespace Kilip\Laravel\Alice;


use Illuminate\Support\ServiceProvider;

class AliceServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}